apiVersion: apps/v1
kind: Deployment
metadata:
  name: oriapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oriapp
  template:
    metadata:
      labels:
        app: oriapp
    spec:
      containers:
      - name: oriapp
        image: milk49/profile-app:latest
        ports:
        - containerPort: 9000
